name: Build Docker file
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the Docker image"
        required: true
        default: ""

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Push Image
        uses: netcracker/qubership-workflow-hub/actions/docker-action@main
        with:
          ref: ${{ github.ref }}
          component: '[{"name": "default", "file": "./alpine/3.11.14/Dockerfile", "context": "."}]'
          custom-image-name: arangodb-source

          tags: "${{ github.event.inputs.tag }}"
          build-args: |
            TAG=${{ github.event.inputs.tag }}
          dry-run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
